# Generated by Django 4.0.2 on 2022-02-06 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tudu', '0002_alter_issue_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='designation',
            field=models.CharField(choices=[('ProjectManager', 'Project-Manager'), ('Developer', 'Developer'), ('Admin', 'Admin')], default='Admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='attachments',
            field=models.ImageField(blank=True, null=True, upload_to='issues_image'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tudu.project'),
        ),
    ]
