# Generated by Django 4.0.2 on 2022-02-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudu', '0004_alter_issue_end_date_alter_issue_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='start_date',
            field=models.DateField(),
        ),
    ]
