# Generated by Django 4.0.2 on 2022-02-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudu', '0007_alter_admin_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('NotStarted', 'NotStarted'), ('Completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('NotStarted', 'NotStarted'), ('Completed', 'Completed')], max_length=20),
        ),
    ]
