# Generated by Django 4.0.2 on 2022-02-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudu', '0008_alter_issue_status_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('NotStarted', 'NotStarted'), ('Pending', 'Pending'), ('Completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('NotStarted', 'NotStarted'), ('Pending', 'Pending'), ('Completed', 'Completed')], max_length=20),
        ),
    ]
