# Generated by Django 4.0.2 on 2022-02-23 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tudu', '0009_alter_issue_status_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('issue_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tudu.issue')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tudu.project')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
