# Generated by Django 4.0.2 on 2022-02-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudu', '0010_taskorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
