# Generated by Django 4.0.2 on 2022-02-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tudu', '0011_project_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order']},
        ),
    ]
