# Generated by Django 4.0.2 on 2022-02-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudu', '0012_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='issue',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
