# Generated by Django 4.0.2 on 2022-03-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tudu', '0013_alter_issue_options_issue_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskOrder',
        ),
    ]
